---
name: Test python setup

"on":
  push:
    paths:
      - '**.py'
      - .github/workflows/test-python-setup.yml
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/test-python-setup.yml

jobs:
  test-python-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip3 install .
